<?php

/*
 +--------------------------------------------------------------------+
 | CiviCRM version 3.3                                                |
 +--------------------------------------------------------------------+
 | Copyright CiviCRM LLC (c) 2004-2010                                |
 +--------------------------------------------------------------------+
 | This file is a part of CiviCRM.                                    |
 |                                                                    |
 | CiviCRM is free software; you can copy, modify, and distribute it  |
 | under the terms of the GNU Affero General Public License           |
 | Version 3, 19 November 2007 and the CiviCRM Licensing Exception.   |
 |                                                                    |
 | CiviCRM is distributed in the hope that it will be useful, but     |
 | WITHOUT ANY WARRANTY; without even the implied warranty of         |
 | MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.               |
 | See the GNU Affero General Public License for more details.        |
 |                                                                    |
 | You should have received a copy of the GNU Affero General Public   |
 | License and the CiviCRM Licensing Exception along                  |
 | with this program; if not, contact CiviCRM LLC                     |
 | at info[AT]civicrm[DOT]org. If you have questions about the        |
 | GNU Affero General Public License or the licensing of CiviCRM,     |
 | see the CiviCRM license FAQ at http://civicrm.org/licensing        |
 +--------------------------------------------------------------------+
*/

/**
 *
 * @package CRM
 * @copyright CiviCRM LLC (c) 2004-2010
 * $Id$
 *
 */
   
function civicrm_SFT_custom_data_civicrm_postProcess( $formName, &$form )
    {
       //echo "<pre>";print_r($form);echo "</pre>"; 
	   //echo $formName;exit;
	   if(($formName=='CRM_Contribute_Form_Contribution_Confirm') && ($form->_id==1 || $form->_id==4 ) )
			{
				//echo $formName;
				//echo "<pre>";print_r($form);echo "</pre>"; 
				if (module_exists('civicrm')) 
				{
				civicrm_initialize(TRUE);
				require_once "CRM/Core/BAO/CustomValueTable.php";
				require_once 'CRM/Utils/Date.php';
			    $params    = array("entityID" => $form->_params['contactID']);
				foreach($form->_fields as $key=>$values)
					{
								if(strstr($key,"custom_"))
									{
										$val="";
										if(is_array($form->_params[$key]))
											{
												$val=SFTconvertarrayTostring($form->_params[$key]);
											}
										else if($values['data_type']=='Date')
											{
												$val=CRM_Utils_Date::processDate( $form->_params[$key]);
											}
										else{
											$val=$form->_params[$key];
											}
										$params = $params  + array($key => $val) ;
									}
					}
				
				$contact = CRM_Core_BAO_CustomValueTable::setValues($params);
				//echo "<pre>";print_r($contact);echo "</pre>";
				}	
				//echo "<pre>";print_r($params);echo "</pre>"; exit;
			}
		
   }
   
   
   
   function SFTconvertarrayTostring($array)
				{
				 $str="";
				 if(is_array($array))
					{
					  foreach($array as $key=>$value)
						{
							if($value==1 && !empty($value))
								$str .= CRM_Core_DAO::VALUE_SEPARATOR . $key . CRM_Core_DAO::VALUE_SEPARATOR;
						}
					}
				   return $str;
				}