<?php
// $Id: school.module,v 1.263.2.4 2009/09/14 10:16:54 goba Exp $

/**
 * @file
 * Enables your site to capture votes on different topics in the form of multiple
 * choice questions.
 */

/**
 * Implementation of hook_perm
 */
function contact_edit_perm() {
  return array('access site-wide', 'edit helpline detail', 'edit my detail', 'administer site-wide');
}


/**
 * Implementation of hook_menu().
 */
function contact_edit_menu() {
 //echo 'hi'; exit;
 $items['edit_my_profile'] = array(
    'title' => 'Edit My Detail',
    'page callback' => 'contact_my_edit_page',
    'access arguments' => array('edit my detail'),
    'type' => MENU_NORMAL_ITEM,
  );
  
  $items['edit_emp_profile'] = array(
    'title' => 'Edit Helpline Detail',
    'page callback' => 'contact_edit_edit_page',
    'access arguments' => array('edit helpline detail'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}


function contact_edit_form_alter(&$form, &$form_state, $form_id){
	//echo "<pre>"; print_r($form); exit;//print_r($form_state); 
	//print_r($form_id); exit; //echo "</pre>"; 
	
	/*if($form_id == 'user_register'){
			//echo 'hello'; exit;
			//$form['account']['name']['#size'] = 30;
			//$form['account']['mail']['#size'] = 30;
			//break;
			$form['account']['fname'] = array('#type' => 'textfield',
				'#title' => t('First Name'),
				'#maxlength' => 100,
				'#default_value' => '',
				'#description' => t("Enter your first name."),
				'#required' => TRUE,
			);
			$form['account']['lname'] = array('#type' => 'textfield',
				'#title' => t('Last Name'),
				'#maxlength' => 100,
				'#default_value' => '',
				'#description' => t("Enter your last name."),
				'#required' => TRUE,
			);
			$form['account']['empname'] = array('#type' => 'textfield',
				'#title' => t('Employer Name'),
				'#maxlength' => 100,
				'#default_value' => '',
				'#description' => t("Enter your employer name."),
				'#required' => TRUE,
			);
			$form['account']['cid'] = array('#type' => 'textfield',
				'#title' => t('Contact ID (cid)'),
				'#maxlength' => 100,
				'#size' => 6,
				'#default_value' => '',
				'#description' => t("Enter your cid."),
				'#required' => TRUE,
			);
	}*/
}

function contact_edit_user($op, &$edit, &$account, $category = NULL) {
	
	// Do the validations
	/*if ($op == 'validate' && $edit['form_id'] == 'user_register') {
		//echo "<pre>"; echo $op; print_r($edit); print_r($account); print_r($category); echo "</pre>"; //exit;
         
         // Validate Contact Information
         $contactID = $account['cid'];
		 
		if (module_exists('civicrm')) {
			civicrm_initialize(TRUE);
				
			require_once "api/v2/Contact.php";
			$params = array(
							'contact_id'		=> $account['cid'],
							'email'   			=> $account['mail'],
							'first_name'		=> $account['fname'],
							'last_name'			=> $account['lname'],
							'current_employer'	=> $account['emp_name'],
							);
			$contacts = civicrm_contact_search( $params );
				
			//echo "<pre>"; print_r($contacts); echo "</pre>"; exit;
			
						
			if(is_array($contacts) && count($contacts) > 0){ }
			else{
				// Display form error
				form_set_error('cid', t('Your credentials does not match'));
			}
		}
		else{
			// civicrm module not exist error
			$msg  = "Error: civicrm module does not exist";
			form_set_error('cid', t($msg));
		}
         
		 
         
    }*/
}


function contact_edit_edit_page() {
	global $user;
		
	$output .= drupal_get_form('contact_edit_edit_form');
	return $output;
	
}

function contact_edit_edit_form()
{
	## just for testing ############################################
	civicrm_initialize(TRUE);
	/*require_once "api/v2/Contact.php";
	$params = array('id'   => 15547, 'return.custom_6'   => 1, );
	$contacts = civicrm_contact_search( $params );
	echo "<pre>"; print_r($contacts); echo "</pre>"; //exit;
		
	require_once "CRM/Core/BAO/CustomValueTable.php";
	$civipar = array("entityID" =>  15547,);
	$civires = CRM_Core_BAO_CustomValueTable::getValues($civipar);
	echo "<pre>"; print_r($civires); echo "</pre>"; //exit;*/
	##################################################################

	
	##################################################################
	######### code start #############################################
	
	############ get user's employer info from civicrm ##########
	global $user;
	
	
	if (module_exists('civicrm')) {
		civicrm_initialize(TRUE);
		require_once "api/v2/Contact.php";
		
		### get contact id from user's emailID ####
		$params = array('email'   => $user->mail,);
		$contacts = civicrm_contact_search( $params );
			foreach($contacts as $cid => $contact){
				break;
			}
		//echo "<pre>"; print_r($contact); echo "</pre>"; exit;
		
		### get contact's employer ID ####
		$params = array('contact_type'   => 'Organization',
						'display_name'   => '"'.$contact['current_employer'].'"',
						);
		$e_contacts = civicrm_contact_search( $params );
			foreach($e_contacts as $eid => $econtact){
				break;
			}
		//echo "<pre>"; print_r($econtact); echo "</pre>"; exit;
		
		### getting employer custom detail ####
		require_once "CRM/Core/BAO/CustomValueTable.php";
		$params = array("entityID" =>  $eid ,'custom_9' => 1 ,'custom_21' => 1 ,'custom_31' => 1 ,
		'custom_32' => 1 ,'custom_33' => 1 ,'custom_34' => 1 ,'custom_35' => 1 ,'custom_36' => 1 ,
		'custom_37' => 1 ,'custom_38' => 1 ,'custom_39' => 1 ,'custom_40' => 1 ,'custom_41' => 1 ,
		'custom_42' => 1 ,'custom_43' => 1 ,'custom_44' => 1 ,'custom_45' => 1 ,'custom_46' => 1 ,
		'custom_47' => 1 ,'custom_48' => 1 ,'custom_49' => 1 ,'custom_50' => 1 ,'custom_51' => 1 ,
		'custom_52' => 1 ,'custom_53' => 1 ,'custom_54' => 1 ,'custom_55' => 1 ,'custom_56' => 1 ,
		'custom_57' => 1 ,'custom_58' => 1 ,'custom_59' => 1 ,'custom_60' => 1 ,'custom_61' => 1 ,
		'custom_62' => 1 ,'custom_63' => 1 ,'custom_64' => 1 ,'custom_65' => 1 ,'custom_66' => 1 ,
		'custom_67' => 1 ,'custom_68' => 1 ,'custom_69' => 1 ,'custom_70' => 1 ,'custom_72' => 1 ,
		'custom_73' => 1 ,'custom_74' => 1 ,'custom_75' => 1 ,'custom_76' => 1 ,'custom_77' => 1 ,
		'custom_78' => 1 ,'custom_79' => 1 ,'custom_80' => 1 ,'custom_81' => 1 ,'custom_82' => 1 ,
		'custom_83' => 1 ,'custom_84' => 1 ,'custom_85' => 1 ,'custom_86' => 1 ,'custom_87' => 1 ,
		'custom_88' => 1 ,'custom_89' => 1,);
		$help_detail = CRM_Core_BAO_CustomValueTable::getValues($params);
		//echo "<pre>"; print_r($help_detail); echo "</pre>"; //exit;
		
		// getting id
		$icount = 1;
		foreach($help_detail as $kfield => $vfield){
			if(substr($kfield, 0, 6) == 'custom')
			{	
				##break;
				$kfield_arr = explode("_", $kfield);
				
				if($icount == count($help_detail)-1)
					$ohours_custom_id = $kfield_arr[2];
				if($icount == count($help_detail))
					$aname_custom_id = $kfield_arr[2];
				if($icount == count($help_detail)-2)
					$custom_id = $kfield_arr[2];
			}
			
			$icount++;
		}
		
		##$kfield_arr = explode("_", $kfield);
		##$custom_id = $kfield_arr[2];
		//echo $aname_custom_id."   ".$custom_id; exit;
		
		
		
		### getting Provider & rated checkbox options ####
		$provider_list	= array();
		$rated_list	= array();
		
		require_once 'CRM/Core/DAO/OptionGroup.php';
        $oGroup =& new CRM_Core_DAO_OptionGroup( );
		$oGroup->whereAdd("label = 'Provider'");
		$oGroup->find(true);
				
		require_once 'CRM/Core/DAO/OptionValue.php';
        $oValue =& new CRM_Core_DAO_OptionValue( );
		$oValue->whereAdd('is_active = 1 AND option_group_id = '.$oGroup->id);
		$oValue->find();
		while($oValue->fetch()){
			//$provider_list[$oValue->id]['value'] 	= $oValue->value;
			//$provider_list[$oValue->id]['name'] 	= $oValue->name;
			//$provider_list[$oValue->id]['label'] 	= $oValue->label;
			$provider_list[$oValue->value] = t($oValue->label);
		}
		
		// rated
		$oGroup =& new CRM_Core_DAO_OptionGroup( );
		$oGroup->whereAdd("label = 'Rated'");
		$oGroup->find(true);
		
		$oValue =& new CRM_Core_DAO_OptionValue( );
		$oValue->whereAdd('is_active = 1 AND option_group_id = '.$oGroup->id);
		$oValue->find();
		while($oValue->fetch()){
			//$rated_list[$oValue->id]['value'] 	= $oValue->value;
			//$rated_list[$oValue->id]['name'] 		= $oValue->name;
			//$rated_list[$oValue->id]['label'] 	= $oValue->label;
			$rated_list[$oValue->value] = t($oValue->label);
		}
		
		##################### Services Provided List ###########################3
		$oGroup =& new CRM_Core_DAO_OptionGroup( );
		$oGroup->whereAdd("id = '75'");
		$oGroup->find(true);
	
		$oValue =& new CRM_Core_DAO_OptionValue( );
		$oValue->whereAdd('is_active = 1 AND option_group_id = '.$oGroup->id);
		$oValue->find();
		while($oValue->fetch()){
			$service_list[$oValue->value] = t($oValue->label);
		}
		#######################################################################
		
		
		##################### Type of organization List ###########################3
		$oGroup =& new CRM_Core_DAO_OptionGroup( );
		$oGroup->whereAdd("id = '72'");
		$oGroup->find(true);
	
		$oValue =& new CRM_Core_DAO_OptionValue( );
		$oValue->whereAdd('is_active = 1 AND option_group_id = '.$oGroup->id);
		$oValue->find();
		while($oValue->fetch()){
			$organ_list[$oValue->value] = t($oValue->label);
		}
		#######################################################################
		
		##################### Type of calls List ###########################3
		$oGroup =& new CRM_Core_DAO_OptionGroup( );
		$oGroup->whereAdd("id = '73'");
		$oGroup->find(true);
	
		$oValue =& new CRM_Core_DAO_OptionValue( );
		$oValue->whereAdd('is_active = 1 AND option_group_id = '.$oGroup->id);
		$oValue->find();
		while($oValue->fetch()){
			$calls_list[$oValue->value] = t($oValue->label);
		}
		#######################################################################
		
		##################### Areas Covered List ###########################3
		$oGroup =& new CRM_Core_DAO_OptionGroup( );
		$oGroup->whereAdd("id = '68'");
		$oGroup->find(true);
	
		$oValue =& new CRM_Core_DAO_OptionValue( );
		$oValue->whereAdd('is_active = 1 AND option_group_id = '.$oGroup->id);
		$oValue->find();
		while($oValue->fetch()){
			$area_list[$oValue->value] = t($oValue->label);
		}
		#######################################################################
		
		##################### Keyword List ###########################3
		$oGroup =& new CRM_Core_DAO_OptionGroup( );
		$oGroup->whereAdd("id = '77'");
		$oGroup->find(true);
	
		$oValue =& new CRM_Core_DAO_OptionValue( );
		$oValue->whereAdd('is_active = 1 AND option_group_id = '.$oGroup->id);
		$oValue->find();
		while($oValue->fetch()){
			$keyword_list[$oValue->value] = t($oValue->label);
		}
		#######################################################################
		
		##################### Offline List ###########################3
		$oGroup =& new CRM_Core_DAO_OptionGroup( );
		$oGroup->whereAdd("id = '78'");
		$oGroup->find(true);
	
		$oValue =& new CRM_Core_DAO_OptionValue( );
		$oValue->whereAdd('is_active = 1 AND option_group_id = '.$oGroup->id);
		$oValue->find();
		while($oValue->fetch()){
			$offline_list[$oValue->value] = t($oValue->label);
		}
		#######################################################################
		
		##################### Online List ###########################3
		$oGroup =& new CRM_Core_DAO_OptionGroup( );
		$oGroup->whereAdd("id = '79'");
		$oGroup->find(true);
	
		$oValue =& new CRM_Core_DAO_OptionValue( );
		$oValue->whereAdd('is_active = 1 AND option_group_id = '.$oGroup->id);
		$oValue->find();
		while($oValue->fetch()){
			$online_list[$oValue->value] = t($oValue->label);
		}
		#######################################################################
		
		
		### getting default provider & rated list
		//const VALUE_SEPERATOR = "";
		
		$default_provider_list	= explode("", $help_detail['custom_10_'.$custom_id]);
		$default_rated_list 	= explode("", $help_detail['custom_12_'.$custom_id]);
		$type_of_service 	= explode("", $help_detail['custom_48']);
		$type_of_org 	= explode("", $help_detail['custom_45']);
		$type_of_calls 	= explode("", $help_detail['custom_46']);
		$keywords_list 	= explode("", $help_detail['custom_50']);
		$keyword_offline 	= explode("", $help_detail['custom_78']);
		$keyword_online 	= explode("", $help_detail['custom_79']);
		$area_covered 	= explode("", $help_detail['custom_88']);
		
		//echo "<pre>"; print_r($type_of_service);  echo "<pre>"; exit;
		
		
		##### getting contact's phone & fax detail
		require_once "CRM/Core/DAO/Phone.php";
		$phone = new CRM_Core_DAO_Phone();
		$phone->whereAdd('contact_id = '.$cid);
		$phone->find();
		
		while($phone->fetch()){
			//echo "<pre>"; print_r($phone); echo "</pre>";
			if($phone->phone_type_id == 1)
				$contact['phone_no'] = $phone->phone;
			else if($phone->phone_type_id == 3)
				$contact['fax_no'] = $phone->phone;
		}
		
		//echo "<pre>"; print_r($contact); echo "</pre>"; exit;
		
		### build employer's edit form ####################
		
		$form['#token'] = $user->uid ? $user->name . $user->mail : '';
		
		$form['empID'] = array('#type' => 'value', '#value' => $eid);
		$form['customID'] = array('#type' => 'value', '#value' => $custom_id);
		$form['aname_customID'] = array('#type' => 'value', '#value' => $aname_custom_id);
		$form['emailID'] = array('#type' => 'value', '#value' => $contact['email_id']);
		$form['cID'] = array('#type' => 'value', '#value' => $cid);
		
		
		######
		$form['helpline_name'] = array('#type' => 'textfield',
		'#title' => t('Name of helpline to appear in directory'),
		'#maxlength' => 255,
		'#size'	=> 50,
		'#default_value' => $help_detail['custom_9'],
		'#prefix' => '<strong><i>Information for Helplines Directory</i></strong>',);
		######
		
		
		#########################
		$form['street_address'] = array('#type' => 'textfield',
		'#title' => t('Address line 1'),
		'#maxlength' => 255,
		'#size'	=> 50,
		'#default_value' => $econtact['street_address'],
		'#prefix' => '<br /><strong><i>Full address with postcode</i></strong>',);
		
		$form['supplemental_address_1'] = array('#type' => 'textfield',
		'#title' => t('Address line 2'),
		'#maxlength' => 255,
		'#size'	=> 50,
		'#default_value' => $econtact['supplemental_address_1'],);
		
		$form['supplemental_address_2'] = array('#type' => 'textfield',
		'#title' => t('Address line 3'),
		'#maxlength' => 255,
		'#size'	=> 50,
		'#default_value' => $econtact['supplemental_address_2'],);
		
		$form['city'] = array('#type' => 'textfield',
		'#title' => t('City'),
		'#maxlength' => 150,
		'#size' => 20,
		'#default_value' => $econtact['city'],);
		
		$form['postal_code'] = array('#type' => 'textfield',
		'#title' => t('Postal Code'),
		'#maxlength' => 150,
		'#size' => 20,
		'#default_value' => $econtact['postal_code'],);
		################
		
		
		
		$form['confidential_address'] = array(
		  '#type' => 'radios',
		  '#title' => t('Click in box if address is confidential and not for publication'),
		  '#default_value' => variable_get($help_detail['custom_52'], 1),
		  '#options' => array(t('Yes'), t('No')),);
		
		#####
		
		$form['additional_name'] = array('#type' => 'textfield',
		'#title' => t('Name of organisation if different from helpline name'),
		'#maxlength' => 255,
		'#size'	=> 50,
		'#default_value' => $help_detail['custom_21'],
		'#prefix' => '<br /> <br /><strong><i>INFORMATION NOT FOR PUBLICATION</i></strong><br>These details are for office use only and will remain confidential to The Helplines Association.',);
	
		
		$form['first_name'] = array('#type' => 'textfield',
		'#title' => t('First Name'),
		'#maxlength' => 255,
		'#size'	=> 50,
		'#default_value' => $contact['first_name'],
		'#prefix' => '<br /><strong><i>Your contact details</i></strong>',);
		
		$form['last_name'] = array('#type' => 'textfield',
		'#title' => t('Last Name'),
		'#maxlength' => 255,
		'#size'	=> 50,
		'#default_value' => $contact['last_name'],);
		
		$form['phone_no'] = array('#type' => 'textfield',
		'#title' => t('Phone'),
		'#maxlength' => 150,
		'#size' => 20,
		'#default_value' => $contact['phone_no'],);
		
		$form['fax_no'] = array('#type' => 'textfield',
		'#title' => t('Fax'),
		'#maxlength' => 150,
		'#size' => 20,
		'#default_value' => $contact['fax_no'],);
		
		$form['email'] = array('#type' => 'textfield',
		'#title' => t('Email'),
		'#maxlength' => 255,
		'#size'	=> 50,
		'#default_value' => $contact['email'],);
		
		/*$form['full_staff'] = array('#type' => 'textfield',
		'#title' => t('Full time paid'),
		'#maxlength' => 255,
		'#size'	=> 50,
		'#default_value' => $help_detail['custom_61'],
		'#prefix' => '<br /><strong><i>How many helpline staff do you have? </i></strong>',);
		
		$form['part_staff'] = array('#type' => 'textfield',
		'#title' => t('Part time paid'),
		'#maxlength' => 255,
		'#size'	=> 50,
		'#default_value' => $help_detail['custom_62'],);
		
		$form['voluntary_staff'] = array('#type' => 'textfield',
		'#title' => t('Voluntary'),
		'#maxlength' => 255,
		'#size'	=> 50,
		'#default_value' => $help_detail['custom_63'],);*/
		
		
		$form['service_provided'] = array(
		'#type' => 'checkboxes',
		'#title' => t('What type of services do you provide?'),
		'#default_value' => $type_of_service,
		'#options' => $service_list,);
		
		
		$form['helpline_no'] = array('#type' => 'textfield',
		'#title' => t('What is your helpline number?'),
		'#maxlength' => 255,
		'#size'	=> 50,
		'#default_value' => $help_detail['custom_40'],
		'#prefix' => 'Please refer to the covering email for our definition of ‘helpline’. If you do not provide a helpline service which meets our definition of ‘helpline’, there is no need to complete the rest of this form, but please return it so that we can exclude your organisation from the Helplines Directory.',);
		
		$form['helpline_sms'] = array('#type' => 'textfield',
		'#title' => t('Helpline SMS (text message) number (if any)'),
		'#maxlength' => 255,
		'#size'	=> 50,
		'#default_value' => $help_detail['custom_41'],);
		
		$form['helpline_email'] = array('#type' => 'textfield',
		'#title' => t('Helpline email address (if any)'),
		'#maxlength' => 255,
		'#size'	=> 50,
		'#default_value' => $help_detail['custom_42'],);
		
		$form['website'] = array('#type' => 'textfield',
		'#title' => t('Web address'),
		'#maxlength' => 255,
		'#size'	=> 50,
		'#default_value' => $help_detail['custom_43'],);
		
		$form['interactive_service'] = array('#type' => 'textfield',
		'#title' => t('Please detail any interactive services'),
		'#maxlength' => 255,
		'#size'	=> 50,
		'#default_value' => $help_detail['custom_58'],);
		
		
		$form['instan_messanger'] = array(
		  '#type' => 'radios',
		  '#title' => t('Do you have an Instant Messenger service? '),
		  '#default_value' => variable_get($help_detail['custom_44'], 1),
		  '#options' => array(t('Yes'), t('No')),);
		
		$form['instant_messanger_id'] = array('#type' => 'textfield',
		'#title' => t('If Yes, how is it accessed?'),
		'#maxlength' => 255,
		'#size'	=> 50,
		'#default_value' => $help_detail['custom_57'],);
		
		
		$form['pub_off_phone'] = array('#type' => 'textfield',
		'#title' => t('Office phone (if different)'),
		'#maxlength' => 255,
		'#size'	=> 50,
		'#default_value' => $help_detail['custom_64'],
		'#prefix' => '<strong><i>Other contact details for publication</i></strong>',);
		
		$form['pub_fax'] = array('#type' => 'textfield',
		'#title' => t('Fax'),
		'#maxlength' => 255,
		'#size'	=> 50,
		'#default_value' => $help_detail['custom_65'],);
		
		$form['pub_textph'] = array('#type' => 'textfield',
		'#title' => t('Text number'),
		'#maxlength' => 255,
		'#size'	=> 50,
		'#default_value' => $help_detail['custom_66'],);
		
		$form['pub_off_email'] = array('#type' => 'textfield',
		'#title' => t('Office (not personal) email'),
		'#maxlength' => 255,
		'#size'	=> 50,
		'#default_value' => $help_detail['custom_67'],);
		
		
		
		$form['type_of_org'] = array(
		'#title' => t('What type of organisation are you?'),
		'#type' => 'checkboxes',
		'#default_value' => $type_of_org,
		'#options' => $organ_list,
		'#prefix' => '<hr>',);
		
		$form['type_of_org_other'] = array('#type' => 'textfield',
		'#title' => t('If Other please describe'),
		'#maxlength' => 255,
		'#size'	=> 50,
		'#default_value' => $help_detail['custom_59'],);
		
		
		$form['take_call'] = array(
		'#title' => t('Are you able to help callers who do not speak English?'),
		'#type' => 'checkboxes',
		'#default_value' => $type_of_calls,
		'#options' => $calls_list,
		'#prefix' => '<hr>',);
		
		$form['take_call_lang'] = array('#type' => 'textfield',
		'#title' => t('If languages other than English are spoken by helpline staff, which ones?'),
		'#maxlength' => 255,
		'#size'	=> 50,
		'#default_value' => $help_detail['custom_60'],);
		
		
		$form['call_sun'] = array('#type' => 'textfield',
		'#title' => t('sunday'),
		'#maxlength' => 255,
		'#size'	=> 50,
		'#default_value' => $help_detail['custom_74'],
		'#prefix' => '<strong><i>Between what hours is your helpline staffed and able to take calls in person?</i></strong><br>Again, please take note of our definition of a helpline before you answer this question. Please only advertise the hours during which you have a sufficient number of staff actively on-duty and ready to take calls. Do not advertise any hours in which your staff are off-duty but ‘on-call’. If you need any clarification about this, please contact Deirdre Rusling on 0141 553 5532 or email deirdre.rusling@helplines.org.uk.',);
		
		$form['call_mon'] = array('#type' => 'textfield',
		'#title' => t('monday'),
		'#maxlength' => 255,
		'#size'	=> 50,
		'#default_value' => $help_detail['custom_68'],);
		
		$form['call_tue'] = array('#type' => 'textfield',
		'#title' => t('tuesday'),
		'#maxlength' => 255,
		'#size'	=> 50,
		'#default_value' => $help_detail['custom_69'],);
		
		$form['call_wed'] = array('#type' => 'textfield',
		'#title' => t('wednesday'),
		'#maxlength' => 255,
		'#size'	=> 50,
		'#default_value' => $help_detail['custom_70'],);
		
		$form['call_thu'] = array('#type' => 'textfield',
		'#title' => t('thursday'),
		'#maxlength' => 255,
		'#size'	=> 50,
		'#default_value' => $help_detail['custom_71'],);
		
		$form['call_fri'] = array('#type' => 'textfield',
		'#title' => t('friday'),
		'#maxlength' => 255,
		'#size'	=> 50,
		'#default_value' => $help_detail['custom_72'],);
		
		$form['call_sat'] = array('#type' => 'textfield',
		'#title' => t('saturday'),
		'#maxlength' => 255,
		'#size'	=> 50,
		'#default_value' => $help_detail['custom_73'],);
		
		$form['call_var'] = array('#type' => 'textfield',
		'#title' => t('If your hours are variable, please tell us how and when your callers can make contact with your service, e.g. do you operate a callback service? If so, please specify times when this operates and when calls will be returned.'),
		'#maxlength' => 255,
		'#size'	=> 50,
		'#default_value' => $help_detail['custom_75'],);
		
		$form['heading_ofline'] = array(
		'#title' => t('offline'),
		'#type' => 'select',
		'#multiple' => TRUE,
		'#default_value' => $keyword_offline,
		'#options' => $offline_list,
		'#prefix' => '<br> <strong><i>which chapter heading your helpline should appear?</i></strong>',);
		
		/*$form['heading_online'] = array(
		'#title' => t('online'),
		'#type' => 'select',
		'#multiple' => TRUE,
		'#default_value' => $keyword_online,
		'#options' => $online_list,);*/
		
		$form['keyword_listing'] = array(
		'#title' => t('Which keywords should we use to index your helpline? Choose a maximum of 10'),
		'#type' => 'checkboxes',
		'#multiple' => TRUE,
		'#default_value' => $keywords_list,
		'#options' => $keyword_list,);
		
		$form['desc_help'] = array('#type' => 'textfield',
		'#title' => t('Please describe briefly your helpline services, including details of any specific client groups targeted. This information will help us to draft your directory entry (maximum 50 words).'),
		'#maxlength' => 255,
		'#size'	=> 50,
		'#default_value' => $help_detail['custom_76'],);
		
		
		$form['desc_service'] = array('#type' => 'textfield',
		'#title' => t('Please describe briefly any other services you run (maximum 50 words).'),
		'#maxlength' => 255,
		'#size'	=> 50,
		'#default_value' => $help_detail['custom_77'],);
		
		$form['serv_sun'] = array('#type' => 'textfield',
		'#title' => t('sunday'),
		'#maxlength' => 255,
		'#size'	=> 50,
		'#default_value' => $help_detail['custom_86'],
		'#prefix' => 'Opening hours for your other services',);
		
		$form['serv_mon'] = array('#type' => 'textfield',
		'#title' => t('monday'),
		'#maxlength' => 255,
		'#size'	=> 50,
		'#default_value' => $help_detail['custom_80'],);
		
		$form['serv_tue'] = array('#type' => 'textfield',
		'#title' => t('tuesday'),
		'#maxlength' => 255,
		'#size'	=> 50,
		'#default_value' => $help_detail['custom_81'],);
		
		$form['serv_wed'] = array('#type' => 'textfield',
		'#title' => t('wednesday'),
		'#maxlength' => 255,
		'#size'	=> 50,
		'#default_value' => $help_detail['custom_82'],);
		
		$form['serv_thu'] = array('#type' => 'textfield',
		'#title' => t('thursday'),
		'#maxlength' => 255,
		'#size'	=> 50,
		'#default_value' => $help_detail['custom_83'],);
		
		$form['serv_fri'] = array('#type' => 'textfield',
		'#title' => t('friday'),
		'#maxlength' => 255,
		'#size'	=> 50,
		'#default_value' => $help_detail['custom_84'],);
		
		$form['serv_sat'] = array('#type' => 'textfield',
		'#title' => t('saturday'),
		'#maxlength' => 255,
		'#size'	=> 50,
		'#default_value' => $help_detail['custom_85'],);
		
		$form['add_comment'] = array('#type' => 'textfield',
		'#title' => t('Please use this space for any additional information or comments '),
		'#maxlength' => 255,
		'#size'	=> 50,
		'#default_value' => $help_detail['custom_87'],);
		
		$form['area_cover'] = array(
		  '#type' => 'checkboxes',
		  '#title' => t('Local Authority Areas Covered by your Helpline<br>(Please check the relevant boxes, but if you cover e.g. the whole of the UK,or the whole of London, there is no need to check the individual councils)'),
		  '#default_value' => $area_covered,
		  '#options' => $area_list,);
		
		
		
		
		
		
		
		
		
		/*
		$form['org_name'] = array('#type' => 'textfield',
		'#title' => t('Organization Name'),
		'#maxlength' => 255,
		'#size'	=> 50,
		'#default_value' => $econtact['organization_name'],
		'#prefix' => '<hr><br /> <br /><strong><i>THA Directory Information</i></strong>',);
		
		$form['legal_name'] = array('#type' => 'textfield',
		'#title' => t('Legal Name'),
		'#maxlength' => 255,
		'#size'	=> 50,
		'#default_value' => $econtact['legal_name'],);*/
		
		/*$form['o_hours'] = array('#type' => 'textfield',
		'#title' => t('Opening Hours'),
		'#maxlength' => 150,
		'#size' => 20,
		'#default_value' => $help_detail['custom_23'],
		'#attributes' => array('readonly' => 'readonly'),);*/
		
		/*$form['o_hours'] = array('#type' => 'textfield',
		'#title' => t('Opening Hours'),
		'#maxlength' => 150,
		'#size' => 20,
		'#default_value' => $help_detail['custom_23'],);*/
		
		
		#####
		



		
		
		
		
		
		
		
		
		
		
		
		
		
		
	
		/*
				
		$form['provider'] = array(
		  '#type' => 'checkboxes',
		  '#title' => t('Provider'),
		  '#default_value' => $default_provider_list,
		  '#options' => $provider_list,);
		
		$form['rated'] = array(
		  '#type' => 'checkboxes',
		  '#title' => t('Rated'),
		  '#default_value' => $default_rated_list,
		  '#options' => $rated_list,);
		*/
		
		
		
		
		


		
		
		
		
		
		
		
		
		
		
		
		/*$form['pdetail_wrapper'] = array(
		'#prefix' => '<div id="pdetail_id">',
		'#suffix' => '</div>',
		'#value' => 'Your contact details',
	     );*/
		 
		
		
		$form['submit'] = array('#type' => 'submit', 
		'#value' => t('Submit'),);

		return $form;
	}
	else{
		// civicrm module not exist
		echo "Error: civicrm module does not exist";
	}
}


function contact_edit_edit_form_validate($form, &$form_state) 
{
    
}

function contact_edit_edit_form_submit($form, &$form_state){
	### update employer's helpline detail ##############
	//echo "<pre>"; print_r($form); print_r($form_state); echo "</pre>"; exit;
	
	$customid			= $form['customID']['#value'];
	$aname_customid		= $form['aname_customID']['#value'];
	$eid				= $form['empID']['#value'];
	$cid				= $form['cID']['#value'];
	$emailid			= $form['emailID']['#value'];
		
	
	################## Form retrive ################
	
	$helpline_name 		= $form['empID']['#post']['helpline_name'];
	
	$street_address 				= $form['empID']['#post']['street_address'];
	$supplemental_address_1 		= $form['empID']['#post']['supplemental_address_1'];
	$supplemental_address_2 		= $form['empID']['#post']['supplemental_address_2'];
	$city 							= $form['empID']['#post']['city'];
	$postal_code 					= $form['empID']['#post']['postal_code'];
	
	$confidential_address 			= $form['empID']['#post']['confidential_address'];
	
	$additional_name 				= $form['empID']['#post']['additional_name'];
	
	$first_name 	= $form['empID']['#post']['first_name'];
	$last_name 		= $form['empID']['#post']['last_name'];
	$phone_no 		= $form['empID']['#post']['phone_no'];
	$fax_no 		= $form['empID']['#post']['fax_no'];
	$email 			= $form['empID']['#post']['email'];
	
	$full_staff 		= $form['empID']['#post']['full_staff'];
	$part_staff 		= $form['empID']['#post']['part_staff'];
	$voluntary_staff 			= $form['empID']['#post']['voluntary_staff'];
	
	$service_provided 	= "".implode("", $form['empID']['#post']['service_provided'])."";
	
	$helpline_no 		= $form['empID']['#post']['helpline_no'];
	$helpline_sms 		= $form['empID']['#post']['helpline_sms'];
	$helpline_email 		= $form['empID']['#post']['helpline_email'];
	$website 		= $form['empID']['#post']['website'];
	$interactive_service 		= $form['empID']['#post']['interactive_service'];
	$instan_messanger 		= $form['empID']['#post']['instan_messanger'];
	$instant_messanger_id 		= $form['empID']['#post']['instant_messanger_id'];
	
	$pub_off_phone 		= $form['empID']['#post']['pub_off_phone'];
	$pub_fax 		= $form['empID']['#post']['pub_fax'];
	$pub_textph 		= $form['empID']['#post']['pub_textph'];
	$pub_off_email 		= $form['empID']['#post']['pub_off_email'];
	
	$type_of_org 	= "".implode("", $form['empID']['#post']['type_of_org'])."";
	$type_of_org_other 		= $form['empID']['#post']['type_of_org_other'];
	
	$take_call 	= "".implode("", $form['empID']['#post']['take_call'])."";
	$take_call_lang 		= $form['empID']['#post']['take_call_lang'];
	
	$call_sun 		= $form['empID']['#post']['call_sun'];
	$call_mon 		= $form['empID']['#post']['call_mon'];
	$call_tue 		= $form['empID']['#post']['call_tue'];
	$call_wed 		= $form['empID']['#post']['call_wed'];
	$call_thu 		= $form['empID']['#post']['call_thu'];
	$call_fri 		= $form['empID']['#post']['call_fri'];
	$call_sat 		= $form['empID']['#post']['call_sat'];
	$call_var 		= $form['empID']['#post']['call_var'];
	
	$heading_ofline 	= "".implode("", $form['empID']['#post']['heading_ofline'])."";
	$heading_online 	= "".implode("", $form['empID']['#post']['heading_online'])."";
	$keyword_list 		= "".implode("", $form['empID']['#post']['keyword_listing'])."";
	
	$desc_help 		= $form['empID']['#post']['desc_help'];
	$desc_service 		= $form['empID']['#post']['desc_service'];
	$serv_sun 		= $form['empID']['#post']['serv_sun'];
	$serv_mon 		= $form['empID']['#post']['serv_mon'];
	$serv_tue 		= $form['empID']['#post']['serv_tue'];
	$serv_wed 		= $form['empID']['#post']['serv_wed'];
	$serv_thu 		= $form['empID']['#post']['serv_thu'];
	$serv_fri 		= $form['empID']['#post']['serv_fri'];
	$serv_sat 		= $form['empID']['#post']['serv_sat'];
	$add_comment 		= $form['empID']['#post']['add_comment'];
	
	$area_cover 	= "".implode("", $form['empID']['#post']['area_cover'])."";
	
	//echo "<pre>".$emailid."  ".$eid."  ".$helpline_no."  ".$helpline_name; print_r($area_cover); print_r($heading_online); echo "</pre>"; exit;
	
	########################################################################
	
	################## Update into custom data fields ######################
	
	if (module_exists('civicrm')) {
		civicrm_initialize(TRUE);
		
		### updating organization helpline detail
		require_once "CRM/Core/BAO/CustomValueTable.php";
		
		$params = array('entityID'			=> $eid,
						'custom_9'			=> $helpline_name,
						'custom_52'			=> $confidential_address,
						'custom_21'			=> $additional_name,
						'custom_61'			=> $full_staff,
						'custom_62'			=> $part_staff,
						'custom_63'			=> $voluntary_staff,
						'custom_48'			=> $service_provided,
						'custom_40'			=> $helpline_no,
						'custom_41'			=> $helpline_sms,
						'custom_42'			=> $helpline_email,
						'custom_43'			=> $website,
						'custom_58'			=> $interactive_service,
						'custom_44'			=> $instan_messanger,
						'custom_57'			=> $instant_messanger_id,
						'custom_64'			=> $pub_off_phone,
						'custom_65'			=> $pub_fax,
						'custom_66'			=> $pub_textph,
						'custom_67'			=> $pub_off_email,
						'custom_45'			=> $type_of_org,
						'custom_59'			=> $type_of_org_other,
						'custom_46'			=> $take_call,
						'custom_60'			=> $take_call_lang ,
						'custom_74'			=> $call_sun,
						'custom_68'			=> $call_mon,
						'custom_69'			=> $call_tue,
						'custom_70'			=> $call_wed,
						'custom_71'			=> $call_thu ,
						'custom_72'			=> $call_fri,
						'custom_73'			=> $call_sat,
						'custom_75'			=> $call_var,
						'custom_78'			=> $heading_ofline,
						'custom_79'			=> $heading_online,
						'custom_50'			=> $keyword_list,
						'custom_76'			=> $desc_help,
						'custom_77'			=> $desc_service,
						'custom_86'			=> $serv_sun,
						'custom_80'			=> $serv_mon,
						'custom_81'			=> $serv_tue,
						'custom_82'			=> $serv_wed ,
						'custom_83'			=> $serv_thu ,
						'custom_84'			=> $serv_fri ,
						'custom_85'			=> $serv_sat,
						'custom_87'			=> $add_comment,
						'custom_88'			=> $area_cover,
						);
		$contact = CRM_Core_BAO_CustomValueTable::setValues($params);
		//echo "<pre>"; print_r($contact); echo "</pre>"; exit;
		
		### update organization's THA info
		require_once "api/v2/Contact.php";
		$params = array(
                    'contact_id'				=> $eid,
                    'organization_name'    		=> $org_name,
                    'legal_name'     			=> $legal_name,
					'home_URL'     				=> $website,
					);
		$contact =&civicrm_contact_update( $params );
		
		### updating organization details
		require_once "CRM/Core/DAO/Address.php";
		$address = new CRM_Core_DAO_Address();
		$address->whereAdd('contact_id = '.$eid.' AND is_primary = 1');
		if($address->find(true)){
			$address->street_address			= $street_address;
			$address->supplemental_address_1	= $supplemental_address_1;
			$address->supplemental_address_2	= $supplemental_address_2;
			$address->city						= $city;
			$address->postal_code				= $postal_code;
			
			$address->update();
		}
		else{
			$address = new CRM_Core_DAO_Address();
			$address->contact_id					= $eid;
			$address->location_type_id			= 1;
			$address->is_primary				= 1;
			$address->street_address			= $street_address;
			$address->supplemental_address_1	= $supplemental_address_1;
			$address->supplemental_address_2	= $supplemental_address_2;
			$address->city						= $city;
			$address->postal_code				= $postal_code;
			$address->insert();
		}
	
		
		### update contact's detail
		require_once "api/v2/Contact.php";
		$params = array(
                    'contact_id'				=> $cid,
                    'first_name'    			=> $first_name,
                    'last_name'     			=> $last_name,
					);
		$contact =&civicrm_contact_update( $params );
		
		### updating contact's phone & fax details
		require_once "CRM/Core/DAO/Phone.php";
		$phone = new CRM_Core_DAO_Phone();
		$phone->whereAdd('contact_id = '.$cid);
		$phone->find();
		
		while($phone->fetch()){
			if($phone->phone_type_id == 1)
				$phone->phone = $phone_no;
			else if($phone->phone_type_id == 3)
				$phone->phone = $fax_no;
				
			$phone->update();
		}
		
		### updating contact's emailID
		global $user;
		//echo "<pre>"; print_r($user); echo "</pre>"; exit;
		if($user->mail != $email){
			## in civi
			require_once "CRM/Core/DAO/Email.php";
			$emailobj = new CRM_Core_DAO_Email();
			$emailobj->get($emailid);
			$emailobj->email = $email;
			$emailobj->update();
			
			## in drupal
			db_query("UPDATE {users} SET mail = '%s' WHERE uid = %d", $email, $user->uid);
		}
		echo "<pre>"; print_r($user); echo "</pre>"; //exit;
		
		form_set_error('err',t('Helpline detail updated.'));
	}
	else{
		// civicrm module not exist
		echo "Error: civicrm module does not exist";
	}

}

############### EDIT MY DETAIL ##################################################
function contact_my_edit_page() {
	global $user;
		
	$output .= drupal_get_form('contact_my_edit_form');
	return $output;
	
}

function contact_my_edit_form()
{
	############ get user's contact id info from civicrm ##########
	global $user;
	
	
	if (module_exists('civicrm')) {
		civicrm_initialize(TRUE);
		require_once "api/v2/Contact.php";
		
		### get contact id from user's emailID ####
		$params = array('email'   => $user->mail,);
		$contacts = civicrm_contact_search( $params );
			foreach($contacts as $cid => $contact){
				break;
			}
		
		### get contact detail
		require_once "CRM/Contact/DAO/Contact.php";
		$contact = new CRM_Contact_DAO_Contact();
		$contact->get($cid);
		$contact->find(true);
		
		### get contact's address
		require_once "CRM/Core/DAO/Address.php";
		$address = new CRM_Core_DAO_Address();
		$address->whereAdd("contact_id = ".$cid." AND is_primary = 1");
		$address->find(true);
		
		//echo "<pre>"; print_r($address); echo "</pre>"; exit;
				
		### build profile edit form ####################
		
		$form['#token'] = $user->uid ? $user->name . $user->mail : '';
		
		$form['cID'] = array('#type' => 'value', '#value' => $cid);
		$form['aID'] = array('#type' => 'value', '#value' => $address->id);
				
		$form['first_name'] = array('#type' => 'textfield',
		'#title' => t('First Name'),
		'#maxlength' => 255,
		'#default_value' => $contact->first_name,);
		
		$form['last_name'] = array('#type' => 'textfield',
		'#title' => t('Last Name'),
		'#maxlength' => 255,
		'#default_value' => $contact->last_name,);
		
		$form['street_address'] = array('#type' => 'textfield',
		'#title' => t('Address line 1'),
		'#maxlength' => 255,
		'#default_value' => $address->street_address,);
		
		$form['supplemental_address_1'] = array('#type' => 'textfield',
		'#title' => t('Address line 2'),
		'#maxlength' => 255,
		'#default_value' => $address->supplemental_address_1,);
		
		$form['supplemental_address_2'] = array('#type' => 'textfield',
		'#title' => t('Address line 3'),
		'#maxlength' => 255,
		'#default_value' => $address->supplemental_address_2,);
		
		$form['city'] = array('#type' => 'textfield',
		'#title' => t('City'),
		'#maxlength' => 150,
		'#size' => 20,
		'#default_value' => $address->city,);
		
		$form['postal_code'] = array('#type' => 'textfield',
		'#title' => t('Postal Code'),
		'#maxlength' => 150,
		'#size' => 20,
		'#default_value' => $address->postal_code,);
		
		$form['submit'] = array('#type' => 'submit', '#value' => t('Update'),);

		return $form;
	}
	else{
		// civicrm module not exist
		echo "Error: civicrm module does not exist";
	}
}


function contact_my_edit_form_validate($form, &$form_state) 
{
    
}

function contact_my_edit_form_submit($form, &$form_state){
	### update employer's helpline detail ##############
	//echo "<pre>"; print_r($form); print_r($form_state); echo "</pre>"; exit;
	
	$cid			= $form['cID']['#value'];
	$aid			= $form['aID']['#value'];
	
	$first_name 				= $form['cID']['#post']['first_name'];
	$last_name 					= $form['cID']['#post']['last_name'];
	$street_address 			= $form['cID']['#post']['street_address'];
	$supplemental_address_1 	= $form['cID']['#post']['supplemental_address_1'];
	$supplemental_address_2 	= $form['cID']['#post']['supplemental_address_2'];
	$city 						= $form['cID']['#post']['city'];
	$postal_code 				= $form['cID']['#post']['postal_code'];
	
	
	### updating contact detail
	if (module_exists('civicrm')) {
		civicrm_initialize(TRUE);
		
		### update contact's detail
		require_once "api/v2/Contact.php";
		$params = array(
                    'contact_id'				=> $cid,
                    'first_name'    			=> $first_name,
                    'last_name'     			=> $last_name,
					);
		$contact =&civicrm_contact_update( $params );
		//echo "<pre>"; print_r($contact); echo "</pre>"; exit;
		
		### update contact's address
		require_once "CRM/Core/DAO/Address.php";
		$address = new CRM_Core_DAO_Address();
		
		if($aid)
			$address->get($aid);
		
		$address->contact_id				= $cid;
		$address->location_type_id			= 1;
		$address->is_primary				= 1;
		$address->street_address			= $street_address;
		$address->supplemental_address_1	= $supplemental_address_1;
		$address->supplemental_address_2	= $supplemental_address_2;
		$address->city						= $city;
		$address->postal_code				= $postal_code;
		
		if($aid)
			$address->update();
		else
			$address->insert();
		
		form_set_error('err',t('Profile updated.'));
	}
	else{
		// civicrm module not exist
		echo "Error: civicrm module does not exist";
	}

}

?>